#!/usr/bin/env python3
"""Generate Haikesi_Dev/GamePlay/Haikesi_ExtAI_Context.lua from SP query builders.

Keeps MP Lua.log CTX wire format identical to FireTuner queries so
parse_overview_response / parse_world_congress_response / parse_leader_views
work unchanged.

Usage (from civ6-mcp-haikesi root):
  uv run python scripts/gen_haikesi_extai_context_lua.py
"""

from __future__ import annotations

from pathlib import Path

from civ_mcp.lua import congress, haikesi, overview
from civ_mcp.lua._helpers import SENTINEL

OUT = (
    Path(__file__).resolve().parents[2]
    / "Haikesi_Dev"
    / "GamePlay"
    / "Haikesi_ExtAI_Context.lua"
)


def _strip_sentinel_print(body: str) -> str:
    body = body.strip()
    needle = f'print("{SENTINEL}")'
    # Remove all SENTINEL prints (trailing + soft-missing WC early exit)
    body = body.replace(needle + "\n", "")
    body = body.replace(needle, "")
    return body.rstrip()


def _overview_fn() -> str:
    body = _strip_sentinel_print(overview.build_overview_query())
    # Parameterize local player → requester id
    body = body.replace(
        "local id = Game.GetLocalPlayer()",
        "local id = requesterPlayerID\n"
        "  if id == nil or id < 0 then id = Game.GetLocalPlayer() end",
        1,
    )
    return f"""
local function dumpOverview(requesterPlayerID)
{body}
end
""".strip()


def _wc_fn() -> str:
    body = _strip_sentinel_print(
        congress.build_world_congress_query(soft_missing=True)
    )
    body = body.replace(
        "local me = Game.GetLocalPlayer()",
        "local me = requesterPlayerID\n"
        "  if me == nil or me < 0 then me = Game.GetLocalPlayer() end",
        1,
    )
    # soft_missing already prints WC_NONE and return — fine inside function
    return f"""
local function dumpWorldCongress(requesterPlayerID)
  pcall(function()
{body}
  end)
end
""".strip()


def _leader_views_fn() -> str:
    # Placeholder ids replaced by runtime viewers table
    body = _strip_sentinel_print(haikesi.build_leader_views_query([999001, 999002]))
    body = body.replace(
        "local viewers = {999001, 999002}",
        "local viewers = viewerIDs",
        1,
    )
    return f"""
local function dumpLeaderViews(viewerIDs)
  if viewerIDs == nil or #viewerIDs == 0 then
    print("RST_MOD|0")
    return
  end
{body}
end
""".strip()


def main() -> None:
    header = """-- Auto-generated by civ6-mcp-haikesi/scripts/gen_haikesi_extai_context_lua.py
-- DO NOT hand-edit wire formats; regenerate from SP FireTuner query builders.
-- Dumps overview + world congress + per-AI leader views into Lua.log for MP ExtAI.

local CTX_BEGIN = "===HAIKESI_EXT_AI_CTX_BEGIN==="
local CTX_END = "===HAIKESI_EXT_AI_CTX_END==="
"""
    footer = """
--- Dump full ExtAI LLM context (same wire lines as SP FireTuner gathers).
-- @param requesterPlayerID number human who triggered the hex
-- @param viewerIDs number[] alive major AI player ids
function Haikesi_DumpExtAIContext(requesterPlayerID, viewerIDs)
  print(CTX_BEGIN)
  pcall(function() dumpOverview(requesterPlayerID) end)
  dumpWorldCongress(requesterPlayerID)
  pcall(function() dumpLeaderViews(viewerIDs or {}) end)
  print(CTX_END)
end

-- Separate AddGameplayScripts files do not share locals; export for GamePlay_Script.
if ExposedMembers ~= nil then
  ExposedMembers.Haikesi_DumpExtAIContext = Haikesi_DumpExtAIContext
end

print("[Haikesi ExtAI Context] dump helpers loaded")
"""
    text = "\n\n".join(
        [
            header.strip(),
            _overview_fn(),
            _wc_fn(),
            _leader_views_fn(),
            footer.strip(),
        ]
    )
    # Soft WC missing uses bare `return` which exits the pcall function — OK.
    OUT.write_text(text + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(text)} chars)")


if __name__ == "__main__":
    main()
