-- Auto-generated by civ6-mcp-haikesi/scripts/gen_haikesi_extai_context_lua.py
-- DO NOT hand-edit wire formats; regenerate from SP FireTuner query builders.
-- Dumps overview + world congress + per-AI leader views into Lua.log for MP ExtAI.

local CTX_BEGIN = "===HAIKESI_EXT_AI_CTX_BEGIN==="
local CTX_END = "===HAIKESI_EXT_AI_CTX_END==="

local function dumpOverview(requesterPlayerID)
local id = requesterPlayerID
  if id == nil or id < 0 then id = Game.GetLocalPlayer() end
local p = Players[id]
local cfg = PlayerConfigurations[id]
local tr = p:GetTreasury()
local te = p:GetTechs()
local cu = p:GetCulture()
local re = p:GetReligion()
local techIdx = te:GetResearchingTech()
local civicIdx = cu:GetProgressingCivic()
local techName = "None"
if techIdx >= 0 then techName = Locale.Lookup(GameInfo.Technologies[techIdx].Name) end
local civicName = "None"
if civicIdx >= 0 then civicName = Locale.Lookup(GameInfo.Civics[civicIdx].Name) end
local nCities = 0; local totalPop = 0; for i, c in p:GetCities():Members() do nCities = nCities + 1; totalPop = totalPop + c:GetPopulation() end
local nUnits = 0
local unitCounts = {}
local unitMaint = 0
for i, u in p:GetUnits():Members() do
    nUnits = nUnits + 1
    local entry = GameInfo.Units[u:GetType()]
    if entry then
        local shortName = Locale.Lookup(entry.Name)
        unitCounts[shortName] = (unitCounts[shortName] or 0) + 1
        unitMaint = unitMaint + (entry.Maintenance or 0)
    end
end
local myScore = p:GetScore()
local favor = p:GetFavor()
local favorPerTurn = 0
local pDiplo = p:GetDiplomacy()
-- 1. Government tier bonus (govRow.Tier is a string like "GOVERNMENT_TIER_1")
local govIdx = cu:GetCurrentGovernment()
if govIdx >= 0 then
    local govRow = GameInfo.Governments[govIdx]
    if govRow and govRow.Tier then
        local n = tonumber(tostring(govRow.Tier):match("(%d+)$")) or 0
        favorPerTurn = favorPerTurn + math.max(1, n)
    end
end
-- 2. Alliances (level-based, +1 per alliance level)
for i = 0, 62 do
    if i ~= id and Players[i] and Players[i]:IsAlive() and Players[i]:IsMajor() and pDiplo:HasMet(i) then
        local ok, ai = pcall(function() return Players[i]:GetDiplomaticAI() end)
        if ok and ai then
            local ok2, stateIdx = pcall(function() return ai:GetDiplomaticStateIndex(id) end)
            if ok2 and stateIdx then
                local si = tonumber(stateIdx) or -1
                if si == 0 then
                    local ok3, aLvl = pcall(function() return pDiplo:GetAllianceLevel(i) end)
                    favorPerTurn = favorPerTurn + (tonumber(ok3 and aLvl) or 1)
                end
            end
        end
    end
end
-- 3. Suzerainties (+1 each)
for i = 0, 62 do
    if Players[i] and Players[i]:IsAlive() then
        local ok, canRecv = pcall(function() return Players[i]:GetInfluence():CanReceiveInfluence() end)
        if ok and canRecv then
            local suzID = Players[i]:GetInfluence():GetSuzerain()
            if suzID == id then favorPerTurn = favorPerTurn + 1 end
        end
    end
end
print(Game.GetCurrentGameTurn() .. "|" .. id .. "|" .. Locale.Lookup(cfg:GetCivilizationShortDescription()):gsub("|", "/") .. "|" .. Locale.Lookup(cfg:GetLeaderName()):gsub("|", "/") .. "|" .. string.format("%.1f", tr:GetGoldBalance()) .. "|" .. string.format("%.1f", tr:GetGoldYield() - tr:GetTotalMaintenance()) .. "|" .. string.format("%.1f", te:GetScienceYield()) .. "|" .. string.format("%.1f", cu:GetCultureYield()) .. "|" .. string.format("%.1f", re:GetFaithBalance()) .. "|" .. techName .. "|" .. civicName .. "|" .. nCities .. "|" .. nUnits .. "|" .. myScore .. "|" .. favor .. "|" .. favorPerTurn .. "|" .. totalPop .. "|" .. string.format("%.1f", tr:GetGoldYield()) .. "|" .. string.format("%.1f", tr:GetTotalMaintenance()))
for i = 0, 62 do
    if i ~= id and Players[i] and Players[i]:IsAlive() and Players[i]:IsMajor() and pDiplo:HasMet(i) then
        local oCfg = PlayerConfigurations[i]
        print("RANK|" .. i .. "|" .. Locale.Lookup(oCfg:GetCivilizationShortDescription()):gsub("|", "/") .. "|" .. Players[i]:GetScore())
    end
end
local pVis = PlayersVisibility[id]
local totalPlots = Map.GetPlotCount()
local revLand, totalLand = 0, 0
for i = 0, totalPlots - 1 do
    local plot = Map.GetPlotByIndex(i)
    if not plot:IsWater() then
        totalLand = totalLand + 1
        if pVis:IsRevealed(plot:GetX(), plot:GetY()) then revLand = revLand + 1 end
    end
end
print("EXPLORE|" .. revLand .. "|" .. totalLand)
local nMajors = 0
local nReligions = 0
for i = 0, 62 do
    if Players[i] and Players[i]:IsMajor() and Players[i]:IsAlive() then
        nMajors = nMajors + 1
        local rType = Players[i]:GetReligion():GetReligionTypeCreated()
        if rType >= 0 then
            nReligions = nReligions + 1
            if i == id or pDiplo:HasMet(i) then
                local rName = "Unknown"
                local rEntry = GameInfo.Religions[rType]
                if rEntry then rName = Locale.Lookup(rEntry.Name) end
                local oCfg = PlayerConfigurations[i]
                local civName = Locale.Lookup(oCfg:GetCivilizationShortDescription())
                print("REL|" .. i .. "|" .. civName .. "|" .. rName)
            end
        end
    end
end
local maxRel = math.floor(nMajors / 2) + 1
print("RELSLOTS|" .. nReligions .. "|" .. maxRel)
local eraManager = Game.GetEras()
local eraIdx = eraManager:GetCurrentEra()
local eraEntry = GameInfo.Eras[eraIdx]
local eraName = eraEntry and Locale.Lookup(eraEntry.Name) or "Unknown"
local eraScore = eraManager:GetPlayerCurrentScore(id)
local darkThresh = eraManager:GetPlayerDarkAgeThreshold(id)
local goldenThresh = eraManager:GetPlayerGoldenAgeThreshold(id)
print("ERA|" .. eraName .. "|" .. eraScore .. "|" .. darkThresh .. "|" .. goldenThresh)
local maxTurns = GameConfiguration.GetValue("GAME_MAX_TURNS") or 0
print("MAXTURNS|" .. maxTurns)
local diffName = "Unknown"
pcall(function()
    local diffHash = PlayerConfigurations[id]:GetHandicapTypeID()
    for d in GameInfo.Difficulties() do
        if GameConfiguration.MakeHash(d.DifficultyType) == diffHash then
            diffName = Locale.Lookup(d.Name)
            break
        end
    end
end)
print("DIFFICULTY|" .. diffName)
local ubParts = {}
for name, count in pairs(unitCounts) do
    table.insert(ubParts, name .. ":" .. count)
end
table.sort(ubParts, function(a, b)
    return tonumber(a:match(":(%d+)$")) > tonumber(b:match(":(%d+)$"))
end)
print("UNITBREAKDOWN|" .. table.concat(ubParts, ",") .. "|" .. unitMaint)
pcall(function()
    -- Prefer GameConfiguration (same as Haikesi ScaleTurn); Game.GetGameSpeedType often fails in scripts
    local gsIdx = GameConfiguration.GetGameSpeedType()
    local gsRow = gsIdx ~= nil and GameInfo.GameSpeeds[gsIdx] or nil
    if not gsRow and Game.GetGameSpeedType then
        gsIdx = Game.GetGameSpeedType()
        gsRow = gsIdx ~= nil and GameInfo.GameSpeeds[gsIdx] or nil
    end
    if gsRow then
        local gsName = Locale.Lookup(gsRow.Name)
        if gsName == nil or gsName == "" or gsName == gsRow.Name then
            gsName = gsRow.GameSpeedType or "Unknown"
        end
        local gsMult = gsRow.CostMultiplier or 100
        print("SPEED|" .. tostring(gsRow.GameSpeedType) .. "|" .. tostring(gsName) .. "|" .. tostring(gsMult))
    end
end)
local vtypes = {"VICTORY_TECHNOLOGY", "VICTORY_CONQUEST", "VICTORY_CULTURE", "VICTORY_RELIGIOUS", "VICTORY_DIPLOMATIC"}
local vEnabled = {}
for _, vt in ipairs(vtypes) do
    local row = GameInfo.Victories[vt]
    if row then
        local ok, en = pcall(function() return Game.IsVictoryEnabled(row.Index) end)
        if ok and en then table.insert(vEnabled, vt) end
    end
end
if #vEnabled < #vtypes then
    print("VENABLED|" .. table.concat(vEnabled, ","))
end
end

local function dumpWorldCongress(requesterPlayerID)
  pcall(function()
local me = requesterPlayerID
  if me == nil or me < 0 then me = Game.GetLocalPlayer() end
local pDiplo = Players[me]:GetDiplomacy()
local wc = Game.GetWorldCongress()
if not wc then print("WC_NONE|not_available")
return end
local inSession = wc:IsInSession()
local meeting = wc:GetMeetingStatus()
local turnsLeft = meeting and meeting.TurnsLeft or -1
local favor = Players[me]:GetFavor()
local costs = wc:GetVotesandFavorCost()
local maxVotes = costs.MaxVotes or 5
local costStr = ""
for i = 0, maxVotes do
    if i > 0 then costStr = costStr .. "," end
    costStr = costStr .. tostring(costs[i] or 0)
end
print("WC_STATUS|" .. tostring(inSession) .. "|" .. turnsLeft .. "|" .. favor .. "|" .. maxVotes .. "|" .. costStr)
local ress = wc:GetResolutions()
if ress then
    for _, res in ipairs(ress) do
        local rType = res.Type
        local gRes = nil
        for row in GameInfo.Resolutions() do
            if row.Hash == rType then gRes = row end
        end
        local typeName = gRes and gRes.ResolutionType or ("HASH_" .. tostring(rType))
        local name = gRes and Locale.Lookup(gRes.Name) or "Unknown"
        local targetKind = gRes and (gRes.TargetKind or "") or ""
        local effectA = gRes and gRes.Effect1Description and Locale.Lookup(gRes.Effect1Description) or ""
        local effectB = gRes and gRes.Effect2Description and Locale.Lookup(gRes.Effect2Description) or ""
        local isPassed = "0"
        local winner = -1
        local chosen = ""
        if not inSession then
            isPassed = "1"
            winner = res.Winner or -1
            if res.ChosenThing then
                if res.TargetType == "PlayerType" then
                    local pid = tonumber(res.ChosenThing)
                    if pid and PlayerConfigurations[pid] and pDiplo:HasMet(pid) then
                        chosen = Locale.Lookup(PlayerConfigurations[pid]:GetCivilizationShortDescription())
                    else
                        chosen = "Unmet Player"
                    end
                else
                    chosen = Locale.Lookup(res.ChosenThing)
                end
            end
        end
        local targets = ""
        if res.PossibleTargets then
            local isPlayerType = (res.TargetType == "PlayerType")
            for ti, tgt in ipairs(res.PossibleTargets) do
                if ti > 1 then targets = targets .. "~" end
                local tName = ""
                local tId = tostring(ti - 1)  -- 0-based index as fallback ID
                if isPlayerType then
                    -- PlayerType: targets are player IDs (numbers)
                    local pid = tonumber(tgt)
                    tId = tostring(pid or (ti - 1))
                    if pid and PlayerConfigurations[pid] and pDiplo:HasMet(pid) then
                        tName = Locale.Lookup(PlayerConfigurations[pid]:GetCivilizationShortDescription())
                    else
                        tName = "Unmet Player"
                    end
                else
                    -- Other types (District, Yield, etc.): targets are LOC key strings
                    local ok, resolved = pcall(Locale.Lookup, tostring(tgt))
                    if ok and resolved then tName = resolved
                    else tName = tostring(tgt) end
                end
                targets = targets .. tId .. ":" .. tName
            end
        end
        effectA = effectA:gsub("|", "/"):gsub("~", "-")
        effectB = effectB:gsub("|", "/"):gsub("~", "-")
        name = name:gsub("|", "/"):gsub("~", "-")
        chosen = chosen:gsub("|", "/"):gsub("~", "-")
        print("WC_RES|" .. rType .. "|" .. typeName .. "|" .. name .. "|" .. targetKind .. "|" .. effectA .. "|" .. effectB .. "|" .. isPassed .. "|" .. winner .. "|" .. chosen .. "|" .. targets)
    end
end
if inSession then
    local props = wc:GetProposals()
    if props then
        for _, prop in ipairs(props) do
            local sid = prop.SenderID or -1
            local tid = prop.TargetID or -1
            local sName = sid >= 0 and Locale.Lookup(PlayerConfigurations[sid]:GetCivilizationShortDescription()) or "Unknown"
            local tName = tid >= 0 and Locale.Lookup(PlayerConfigurations[tid]:GetCivilizationShortDescription()) or "Unknown"
            local pType = prop.Type or 0
            local desc = prop.Description and Locale.Lookup(prop.Description) or ""
            desc = desc:gsub("|", "/"):gsub("~", "-")
            sName = sName:gsub("|", "/")
            tName = tName:gsub("|", "/")
            print("WC_PROP|" .. sid .. "|" .. sName .. "|" .. tid .. "|" .. tName .. "|" .. pType .. "|" .. desc)
        end
    end
end
  end)
end

local function dumpLeaderViews(viewerIDs)
  if viewerIDs == nil or #viewerIDs == 0 then
    print("RST_MOD|0")
    return
  end
local viewers = viewerIDs
local states = {"ALLIED","DECLARED_FRIEND","FRIENDLY","NEUTRAL","UNFRIENDLY","DENOUNCED","WAR"}
-- GetDiplomaticStateIndex / GetGrievancesAgainst 仅 UI；联机 CTX 在 Gameplay，需 Script API + UI 缓存
local function shortDiploState(raw)
  if raw == nil then return nil end
  local s = tostring(raw)
  s = s:gsub("^DIPLO_STATE_", "")
  if s == "ALLIED" or s == "DECLARED_FRIEND" or s == "FRIENDLY" or s == "NEUTRAL"
      or s == "UNFRIENDLY" or s == "DENOUNCED" or s == "WAR" then
    return s
  end
  return nil
end
local function readUiDipPacked(fromId, towardId)
  local key = tostring(fromId) .. "_" .. tostring(towardId)
  if ExposedMembers ~= nil and ExposedMembers.Haikesi_UIDipByPair ~= nil then
    local packed = ExposedMembers.Haikesi_UIDipByPair[key]
    if packed ~= nil and tostring(packed) ~= "" then
      return tostring(packed)
    end
  end
  local prop = Game:GetProperty("PROP_NW_HAIKESI_UI_DIP_" .. key)
  if prop ~= nil and tostring(prop) ~= "" then
    return tostring(prop)
  end
  return nil
end
local function resolveDiploStateName(fromId, towardId, atWar)
  -- fromId 对 towardId 的观感（与旧逻辑：对方 AI 看 viewer 一致 → 调用处传 tid, vid）
  -- 交战/同盟以 Script Diplomacy 为准（Index API 在 Gameplay 常空/恒 0）
  local name = nil
  pcall(function()
    local d = Players[fromId]:GetDiplomacy()
    if d == nil then return end
    if atWar or (d.IsAtWarWith and d:IsAtWarWith(towardId)) then
      name = "WAR"
    elseif d.HasAllied and d:HasAllied(towardId) then
      name = "ALLIED"
    elseif d.HasDeclaredFriendship and d:HasDeclaredFriendship(towardId) then
      name = "DECLARED_FRIEND"
    end
  end)
  if name == nil then
    local packed = readUiDipPacked(fromId, towardId)
    if packed ~= nil then
      local st = string.match(packed, "^([^;]*);")
      name = shortDiploState(st) or st
    end
  end
  if name == nil then
    pcall(function()
      local ai = Players[fromId]:GetDiplomaticAI()
      if ai == nil then return end
      if ai.GetDiplomaticStateIndex ~= nil then
        local idx = ai:GetDiplomaticStateIndex(towardId)
        if idx ~= nil then
          local row = GameInfo.DiplomaticStates[idx]
          if row and row.StateType then
            name = shortDiploState(row.StateType)
          end
          if name == nil then
            name = states[(tonumber(idx) or -1) + 1]
          end
        end
      end
      if name == nil and ai.GetDiplomaticState ~= nil then
        local st = ai:GetDiplomaticState(towardId)
        name = shortDiploState(st)
        if name == nil and st ~= nil then
          local row = GameInfo.DiplomaticStates[st]
          if row and row.StateType then
            name = shortDiploState(row.StateType)
          else
            for r in GameInfo.DiplomaticStates() do
              if r.Hash == st or r.Index == st then
                name = shortDiploState(r.StateType)
                break
              end
            end
          end
        end
      end
    end)
  end
  if atWar then
    name = "WAR"
  end
  return name or "NEUTRAL"
end
local function resolveGrievances(fromId, towardId)
  -- GetGrievancesAgainst 仅 UI；Gameplay 直调常 nil → 优先读 UI 缓存
  local packed = readUiDipPacked(fromId, towardId)
  if packed ~= nil then
    local _, _, gr = string.match(packed, "^([^;]*);([^;]*);([^;]*)$")
    if gr ~= nil then return tonumber(gr) or 0 end
  end
  local g = nil
  pcall(function()
    local d = Players[fromId]:GetDiplomacy()
    if d and d.GetGrievancesAgainst then
      g = d:GetGrievancesAgainst(towardId)
    end
  end)
  if g ~= nil then return tonumber(g) or 0 end
  return 0
end
local function resolveRelScore(fromId, towardId)
  -- GetDiplomaticScore 在 Gameplay 常恒 0；优先 UI 缓存，避免挡住真实分数
  local packed = readUiDipPacked(fromId, towardId)
  if packed ~= nil then
    local _, sc, _ = string.match(packed, "^([^;]*);([^;]*);([^;]*)$")
    if sc ~= nil then
      local n = tonumber(sc)
      if n ~= nil then return n end
    end
  end
  local score = 0
  local got = false
  pcall(function()
    local ai = Players[fromId]:GetDiplomaticAI()
    if ai == nil then return end
    if ai.GetDiplomaticScore ~= nil then
      local s = ai:GetDiplomaticScore(towardId)
      if s ~= nil then score = tonumber(s) or 0; got = true; return end
    end
    if ai.GetDiplomaticModifiers ~= nil then
      local mods = ai:GetDiplomaticModifiers(towardId)
      if mods then
        local sum = 0
        for _, mod in ipairs(mods) do sum = sum + (mod.Score or 0) end
        score = sum
        got = true
      end
    end
  end)
  if got then return score end
  return 0
end
local function safeLookup(key)
  if not key or key == "" then return "" end
  local ok, t = pcall(function() return Locale.Lookup(key) end)
  if ok and t and t ~= "" then return tostring(t):gsub("|","/") end
  return tostring(key):gsub("|","/")
end
-- Real Strategy soft dependency (Infixo): ExposedMembers.RST.Data
local rstMod = 0
pcall(function()
  local RST = ExposedMembers.RST
  if RST and RST.Data then rstMod = 1 end
end)
print("RST_MOD|" .. rstMod)
local function printRst(vid)
  if rstMod ~= 1 then return end
  pcall(function()
    local d = ExposedMembers.RST.Data[vid]
    if not d then return end
    local active = tostring(d.ActiveStrategy or "NONE")
    local pri = d.Priorities or {}
    local def, catch = -1, -1
    if d.ActiveDefense ~= nil then def = d.ActiveDefense and 1 or 0 end
    if d.ActiveCatching ~= nil then catch = d.ActiveCatching and 1 or 0 end
    print("RST|" .. vid .. "|" .. active
      .. "|" .. string.format("%.1f", tonumber(pri.CONQUEST) or 0)
      .. "|" .. string.format("%.1f", tonumber(pri.SCIENCE) or 0)
      .. "|" .. string.format("%.1f", tonumber(pri.CULTURE) or 0)
      .. "|" .. string.format("%.1f", tonumber(pri.RELIGION) or 0)
      .. "|" .. string.format("%.1f", tonumber(pri.DIPLO) or 0)
      .. "|" .. def .. "|" .. catch)
  end)
end
local function printFaith(vid)
  local panType, panName = "NONE", ""
  local relType, relName = "NONE", ""
  pcall(function()
    local pr = Players[vid]:GetReligion()
    local pan = pr:GetPantheon()
    if pan and pan >= 0 and GameInfo.Beliefs[pan] then
      local b = GameInfo.Beliefs[pan]
      panType = b.BeliefType
      panName = safeLookup(b.Name)
    end
    local rt = pr:GetReligionTypeCreated()
    if rt and rt >= 0 and GameInfo.Religions[rt] then
      local r = GameInfo.Religions[rt]
      if r.ReligionType ~= "RELIGION_PANTHEON" then
        relType = r.ReligionType
        relName = safeLookup(r.Name)
      end
    end
  end)
  local cfg = PlayerConfigurations[vid]
  local civName = cfg and safeLookup(cfg:GetCivilizationShortDescription()) or ""
  local leaderName = cfg and safeLookup(cfg:GetLeaderName()) or ""
  print("FAITH|" .. vid .. "|" .. civName .. "|" .. leaderName
    .. "|" .. panType .. "|" .. panName .. "|" .. relType .. "|" .. relName)
  if panType ~= "NONE" and GameInfo.Beliefs[panType] then
    local b = GameInfo.Beliefs[panType]
    local desc = safeLookup(b.Description):gsub("\n", " ")
    print("FBELIEF|" .. vid .. "|BELIEF_CLASS_PANTHEON|" .. panType .. "|" .. panName .. "|" .. desc)
  end
  pcall(function()
    local religions = Game.GetReligion():GetReligions()
    if not religions then return end
    for _, religion in ipairs(religions) do
      if religion.Founder == vid and religion.Beliefs then
        for _, beliefIdx in ipairs(religion.Beliefs) do
          local b = GameInfo.Beliefs[beliefIdx]
          if b and b.BeliefClassType ~= "BELIEF_CLASS_PANTHEON" then
            local desc = safeLookup(b.Description):gsub("\n", " ")
            print("FBELIEF|" .. vid .. "|" .. tostring(b.BeliefClassType)
              .. "|" .. b.BeliefType .. "|" .. safeLookup(b.Name) .. "|" .. desc)
          end
        end
      end
    end
  end)
end
-- GetNumTechsResearched / 军力·旅游·外交VP 在 Gameplay 常空；优先 UI 缓存。
-- 军力：失败返回 -1（未知），禁止用假 0 冒充「无军队」。
local function countTechsResearched(p)
  local n = nil
  pcall(function()
    local te = p:GetTechs()
    if te == nil then return end
    if te.GetNumTechsResearched ~= nil then
      n = tonumber(te:GetNumTechsResearched())
      return
    end
    local c = 0
    for row in GameInfo.Technologies() do
      if te:HasTech(row.Index) then c = c + 1 end
    end
    n = c
  end)
  return n
end
local function countCivicsCompleted(p)
  local n = nil
  pcall(function()
    local cu = p:GetCulture()
    if cu == nil then return end
    if cu.GetNumCivicsCompleted ~= nil then
      n = tonumber(cu:GetNumCivicsCompleted())
      return
    end
    local c = 0
    for row in GameInfo.Civics() do
      if cu:HasCivic(row.Index) then c = c + 1 end
    end
    n = c
  end)
  return n
end
local function readUiVstatPacked(pid)
  if ExposedMembers ~= nil and ExposedMembers.Haikesi_UIVstatByPlayer ~= nil then
    local packed = ExposedMembers.Haikesi_UIVstatByPlayer[pid]
    if packed ~= nil and tostring(packed) ~= "" then
      return tostring(packed)
    end
  end
  local prop = Game:GetProperty("PROP_NW_HAIKESI_UI_VSTAT_" .. tostring(pid))
  if prop ~= nil and tostring(prop) ~= "" then
    return tostring(prop)
  end
  return nil
end
local function printTrade(vid)
  local packed = nil
  if ExposedMembers ~= nil and ExposedMembers.Haikesi_UITradeSumByPlayer ~= nil then
    packed = ExposedMembers.Haikesi_UITradeSumByPlayer[vid]
      or ExposedMembers.Haikesi_UITradeSumByPlayer[tostring(vid)]
  end
  if packed == nil or tostring(packed) == "" then
    packed = Game:GetProperty("PROP_NW_HAIKESI_UI_TRADE_" .. tostring(vid))
  end
  if packed == nil or tostring(packed) == "" then
    print("TRADE|" .. vid .. "|-1|-1|-1|-1|-1")
    return
  end
  local cap, outN, dom, intlOut, intlIn = string.match(
    tostring(packed), "^(%-?%d+);(%-?%d+);(%-?%d+);(%-?%d+);(%-?%d+)$")
  if cap == nil then
    print("TRADE|" .. vid .. "|-1|-1|-1|-1|-1")
    return
  end
  print("TRADE|" .. vid .. "|" .. cap .. "|" .. outN .. "|" .. dom
    .. "|" .. intlOut .. "|" .. intlIn)
  if tonumber(cap) ~= nil and tonumber(cap) < 0 then
    return
  end
  local routes = nil
  if ExposedMembers ~= nil and ExposedMembers.Haikesi_UITradeRoutesByPlayer ~= nil then
    routes = ExposedMembers.Haikesi_UITradeRoutesByPlayer[vid]
      or ExposedMembers.Haikesi_UITradeRoutesByPlayer[tostring(vid)]
  end
  if type(routes) == "table" then
    for _, body in ipairs(routes) do
      if body ~= nil and tostring(body) ~= "" then
        print("TROUTE|" .. vid .. "|" .. tostring(body))
      end
    end
    return
  end
  local routeProp = Game:GetProperty("PROP_NW_HAIKESI_UI_TROUTES_" .. tostring(vid))
  if routeProp ~= nil and tostring(routeProp) ~= "" then
    for body in string.gmatch(tostring(routeProp), "[^#]+") do
      if body ~= "" then
        print("TROUTE|" .. vid .. "|" .. body)
      end
    end
  end
end
local function resolveMilitaryStrength(pid, p)
  -- 优先 UI 缓存（仅在 UI 成功读到时写入；缺键=未知）
  if ExposedMembers ~= nil and ExposedMembers.Haikesi_UIMilitaryByPlayer ~= nil then
    local cached = ExposedMembers.Haikesi_UIMilitaryByPlayer[pid]
    if cached ~= nil then
      return tonumber(cached) or 0
    end
  end
  local prop = Game:GetProperty("PROP_NW_HAIKESI_UI_MIL_" .. tostring(pid))
  if prop ~= nil then
    local n = tonumber(prop)
    if n ~= nil then return n end
  end
  local mil = nil
  pcall(function()
    local st = p:GetStats()
    if st.GetMilitaryStrengthWithoutTreasury ~= nil then
      mil = st:GetMilitaryStrengthWithoutTreasury()
    elseif st.GetMilitaryStrength ~= nil then
      mil = st:GetMilitaryStrength()
    end
  end)
  if mil == nil then return -1 end
  return tonumber(mil) or -1
end
local function printVStat(vid, tid, civName)
  pcall(function()
    local p = Players[tid]
    if not p then return end
    local st = p:GetStats()
    local sciVP, sciNeed, diploVP, tourism = 0, 50, 0, 0
    local milStr, techs, civics, relCities, stay, visiting = -1, -1, -1, 0, 0, 0
    local score, spaceports, holds = 0, 0, 1
    pcall(function() score = p:GetScore() end)
    pcall(function() sciVP = st:GetScienceVictoryPoints() or 0 end)
    pcall(function() sciNeed = st:GetScienceVictoryPointsTotalNeeded() or 50 end)
    pcall(function() diploVP = st:GetDiplomaticVictoryPoints() or 0 end)
    pcall(function() tourism = st:GetTourism() or 0 end)
    pcall(function() stay = p:GetCulture():GetStaycationers() or 0 end)
    pcall(function() visiting = p:GetCulture():GetTouristsTo() or 0 end)
    -- packed: diplo;tourism;stay;favor;visiting[;techs;civics]（后两段可空=未知）
    local packed = readUiVstatPacked(tid)
    if packed ~= nil then
      local parts = {}
      local start = 1
      while true do
        local i = string.find(packed, ";", start, true)
        if not i then
          table.insert(parts, string.sub(packed, start))
          break
        end
        table.insert(parts, string.sub(packed, start, i - 1))
        start = i + 1
      end
      if parts[1] ~= nil then diploVP = tonumber(parts[1]) or diploVP end
      if parts[2] ~= nil then tourism = tonumber(parts[2]) or tourism end
      if parts[3] ~= nil then stay = tonumber(parts[3]) or stay end
      if parts[5] ~= nil and parts[5] ~= "" then visiting = tonumber(parts[5]) or visiting end
      if parts[6] ~= nil and parts[6] ~= "" then techs = tonumber(parts[6]) or techs end
      if parts[7] ~= nil and parts[7] ~= "" then civics = tonumber(parts[7]) or civics end
    end
    milStr = resolveMilitaryStrength(tid, p)
    if techs < 0 then
      local n = countTechsResearched(p)
      if n ~= nil then techs = n else techs = -1 end
    end
    if civics < 0 then
      local n = countCivicsCompleted(p)
      if n ~= nil then civics = n else civics = -1 end
    end
    pcall(function() relCities = st:GetNumCitiesFollowingReligion() or 0 end)
    pcall(function()
      for _, city in p:GetCities():Members() do
        for _, d in city:GetDistricts():Members() do
          local dInfo = GameInfo.Districts[d:GetType()]
          if dInfo and dInfo.DistrictType == "DISTRICT_SPACEPORT" and d:IsComplete() then
            spaceports = spaceports + 1
          end
        end
      end
    end)
    pcall(function()
      local cap = p:GetCities():GetCapitalCity()
      if cap and not cap:IsOriginalCapital() then holds = 0 end
      if not cap then holds = 0 end
    end)
    print("VSTAT|" .. vid .. "|" .. tid .. "|" .. civName
      .. "|" .. score .. "|" .. sciVP .. "|" .. sciNeed .. "|" .. diploVP
      .. "|" .. math.floor(tonumber(tourism) or 0) .. "|" .. milStr .. "|" .. techs .. "|" .. civics
      .. "|" .. relCities .. "|" .. spaceports .. "|" .. holds .. "|" .. stay
      .. "|" .. visiting)
  end)
end
local hashName = {}
for u in GameInfo.Units() do hashName[u.Hash] = u.UnitType end
for b in GameInfo.Buildings() do hashName[b.Hash] = b.BuildingType end
for d in GameInfo.Districts() do hashName[d.Hash] = d.DistrictType end
for p in GameInfo.Projects() do hashName[p.Hash] = p.ProjectType end
local function prodLabel(typeKey)
  if not typeKey or typeKey == "" or typeKey == "nothing" then return "IDLE" end
  local row = GameInfo.Units[typeKey] or GameInfo.Buildings[typeKey] or GameInfo.Districts[typeKey] or GameInfo.Projects[typeKey]
  if row and row.Name then return safeLookup(row.Name) end
  return tostring(typeKey):gsub("UNIT_",""):gsub("BUILDING_",""):gsub("DISTRICT_",""):gsub("PROJECT_","")
end
local function yieldTriple(p)
  local sci, cul, gold = 0, 0, 0
  pcall(function() sci = p:GetTechs():GetScienceYield() end)
  pcall(function() cul = p:GetCulture():GetCultureYield() end)
  pcall(function()
    gold = p:GetTreasury():GetGoldYield() - p:GetTreasury():GetTotalMaintenance()
  end)
  return sci, cul, gold
end
local function empireStats(pid)
  local p = Players[pid]
  local score = 0
  pcall(function() score = p:GetScore() end)
  local nCities, totalPop = 0, 0
  pcall(function()
    for _, c in p:GetCities():Members() do
      nCities = nCities + 1
      totalPop = totalPop + c:GetPopulation()
    end
  end)
  local sci, cul, gold = yieldTriple(p)
  local mil = resolveMilitaryStrength(pid, p)
  local techs = countTechsResearched(p)
  local civics = countCivicsCompleted(p)
  if techs == nil then techs = -1 end
  if civics == nil then civics = -1 end
  -- VIEWER 也吃 UI 科技/市政缓存（Gameplay 遍历 HasTech 常失败→假 0）
  local packed = readUiVstatPacked(pid)
  if packed ~= nil then
    local parts = {}
    local start = 1
    while true do
      local i = string.find(packed, ";", start, true)
      if not i then
        table.insert(parts, string.sub(packed, start))
        break
      end
      table.insert(parts, string.sub(packed, start, i - 1))
      start = i + 1
    end
    if parts[6] ~= nil and parts[6] ~= "" then techs = tonumber(parts[6]) or techs end
    if parts[7] ~= nil and parts[7] ~= "" then civics = tonumber(parts[7]) or civics end
  end
  local faith = 0
  pcall(function() faith = p:GetReligion():GetFaithYield() end)
  local research, civic = "无", "无"
  pcall(function()
    local t = p:GetTechs():GetResearchingTech()
    if t and t >= 0 and GameInfo.Technologies[t] then
      research = safeLookup(GameInfo.Technologies[t].Name)
    end
  end)
  pcall(function()
    local c = p:GetCulture():GetProgressingCivic()
    if c and c >= 0 and GameInfo.Civics[c] then
      civic = safeLookup(GameInfo.Civics[c].Name)
    end
  end)
  return score, nCities, totalPop, sci, cul, gold, mil, techs, civics, faith, research, civic
end
local function printTraits(vid, leaderType, civType)
  if leaderType and leaderType ~= "" then
    for row in GameInfo.LeaderTraits() do
      if row.LeaderType == leaderType then
        local tr = GameInfo.Traits[row.TraitType]
        if tr and tr.Name and tr.Description then
          local n = safeLookup(tr.Name)
          local d = safeLookup(tr.Description)
          if n ~= "" and d ~= "" and not string.find(n, "^LOC_") and not string.find(d, "^LOC_")
             and not string.find(tostring(tr.TraitType), "MAJOR_CIV")
             and not string.find(tostring(tr.TraitType), "IGNORE") then
            print("TRAIT|" .. vid .. "|LEADER|" .. n .. "|" .. d)
          end
        end
      end
    end
  end
  if civType and civType ~= "" then
    for row in GameInfo.CivilizationTraits() do
      if row.CivilizationType == civType then
        local tr = GameInfo.Traits[row.TraitType]
        if tr and tr.Name and tr.Description then
          local n = safeLookup(tr.Name)
          local d = safeLookup(tr.Description)
          if n ~= "" and d ~= "" and not string.find(n, "^LOC_") and not string.find(d, "^LOC_")
             and not string.find(tostring(tr.TraitType), "MAJOR_CIV")
             and not string.find(tostring(tr.TraitType), "IGNORE") then
            print("TRAIT|" .. vid .. "|CIV|" .. n .. "|" .. d)
          end
        end
      end
    end
  end
end
local function printAgendas(vid, leaderType)
  -- 历史议程来自静态表，不依赖 GetAgendaTypes（联机 Gameplay 常拿不到）
  local seen = {}
  if leaderType and leaderType ~= "" then
    for ha in GameInfo.HistoricalAgendas() do
      if ha.LeaderType == leaderType then
        local aDef = GameInfo.Agendas[ha.AgendaType]
        if aDef then
          local n = safeLookup(aDef.Name)
          local d = safeLookup(aDef.Description)
          if n ~= "" and d ~= "" and not string.find(n, "^LOC_") and not string.find(d, "^LOC_") then
            print("AGENDA|" .. vid .. "|" .. n .. "|" .. d)
            seen[aDef.Index] = true
            seen[ha.AgendaType] = true
          end
        end
      end
    end
  end
  -- 随机议程：仅当 API 可用时补全（领袖自己应知道）
  local okAg, agendas = pcall(function() return Players[vid]:GetAgendaTypes() end)
  if okAg and agendas then
    for _, agIdx in pairs(agendas) do
      if not seen[agIdx] then
        local aDef = GameInfo.Agendas[agIdx]
        if aDef and not seen[aDef.Index] then
          local n = safeLookup(aDef.Name)
          local d = safeLookup(aDef.Description)
          if n ~= "" and d ~= "" and not string.find(n, "^LOC_") and not string.find(d, "^LOC_") then
            print("AGENDA|" .. vid .. "|" .. n .. "|" .. d)
            seen[aDef.Index] = true
          end
        end
      end
    end
  end
end
for _, vid in ipairs(viewers) do
  if Players[vid] and Players[vid]:IsAlive() and Players[vid]:IsMajor() then
    local cfg = PlayerConfigurations[vid]
    local civName = safeLookup(cfg:GetCivilizationShortDescription())
    local leaderName = safeLookup(cfg:GetLeaderName())
    local leaderType = ""
    local civType = ""
    pcall(function() leaderType = cfg:GetLeaderTypeName() end)
    pcall(function() civType = cfg:GetCivilizationTypeName() end)
    local score, cities, pop, sci, cul, gold, mil, techs, civics, faith, research, civic = empireStats(vid)
    local favor = 0
    pcall(function() favor = Players[vid]:GetFavor() or 0 end)
    -- GetFavor 在 Gameplay 常 0；外交条 Favor 来自 UI 缓存第四段
    if (tonumber(favor) or 0) == 0 then
      local packed = readUiVstatPacked(vid)
      if packed ~= nil then
        local _, _, _, f = string.match(
          packed, "^([^;]*);([^;]*);([^;]*);([^;]*);?([^;]*)$")
        if f ~= nil then favor = tonumber(f) or 0 end
      end
    end
    print("VIEWER|" .. vid .. "|" .. civName .. "|" .. leaderName
      .. "|" .. score .. "|" .. cities .. "|" .. pop
      .. "|" .. string.format("%.1f", sci) .. "|" .. string.format("%.1f", cul) .. "|" .. string.format("%.1f", gold)
      .. "|" .. mil .. "|" .. techs .. "|" .. civics .. "|" .. string.format("%.1f", faith)
      .. "|" .. research .. "|" .. civic .. "|" .. favor)
    printTraits(vid, leaderType, civType)
    printAgendas(vid, leaderType)
    printRst(vid)
    printFaith(vid)
    printVStat(vid, vid, civName)
    printTrade(vid)
    pcall(function()
      for _, c in Players[vid]:GetCities():Members() do
        local cID = c:GetID()
        local cName = safeLookup(c:GetName())
        local cPop = c:GetPopulation()
        local g = c:GetGrowth()
        local producing = "nothing"
        local turnsLeft = 0
        pcall(function()
          local bq = c:GetBuildQueue()
          if bq:GetSize() > 0 then
            local h = bq:GetCurrentProductionTypeHash()
            if h and h ~= 0 then
              producing = hashName[h] or "UNKNOWN"
              turnsLeft = bq:GetTurnsLeft() or 0
            end
          end
        end)
        local dStr = ""
        pcall(function()
          for _, d in c:GetDistricts():Members() do
            local dInfo = GameInfo.Districts[d:GetType()]
            if dInfo and dInfo.DistrictType ~= "DISTRICT_CITY_CENTER" then
              local short = safeLookup(dInfo.Name)
              if short == "" then short = dInfo.DistrictType:gsub("DISTRICT_", "") end
              dStr = dStr .. (dStr ~= "" and "," or "") .. short
            end
          end
        end)
        local amNeed, amTotal, housing = 0, 0, 0
        pcall(function()
          amNeed = g:GetAmenitiesNeeded() or 0
          amTotal = amNeed + (g:GetAmenities() or 0)
          housing = g:GetHousing() or 0
        end)
        local loyalty = 100
        pcall(function()
          local ci = c:GetCulturalIdentity()
          if ci then loyalty = ci:GetLoyalty() or 100 end
        end)
        print("CITY|" .. vid .. "|" .. cID .. "|" .. cName .. "|" .. cPop
          .. "|" .. string.format("%.1f", c:GetYield(0))
          .. "|" .. string.format("%.1f", c:GetYield(1))
          .. "|" .. string.format("%.1f", c:GetYield(2))
          .. "|" .. string.format("%.1f", c:GetYield(3))
          .. "|" .. string.format("%.1f", c:GetYield(4))
          .. "|" .. string.format("%.1f", c:GetYield(5))
          .. "|" .. string.format("%.1f", housing)
          .. "|" .. amTotal .. "|" .. amNeed
          .. "|" .. dStr .. "|" .. prodLabel(producing) .. "|" .. turnsLeft
          .. "|" .. string.format("%.0f", loyalty))
      end
    end)
    local pDiplo = Players[vid]:GetDiplomacy()
    for tid = 0, 62 do
      if tid ~= vid and Players[tid] and Players[tid]:IsAlive() and Players[tid]:IsMajor() then
        local met = false
        pcall(function() met = pDiplo:HasMet(tid) end)
        if met then
          local tcfg = PlayerConfigurations[tid]
          local tciv = safeLookup(tcfg:GetCivilizationShortDescription())
          local tleader = safeLookup(tcfg:GetLeaderName())
          local tscore, tcities, tpop, tsci, tcul, tgold, tmil, ttechs, tcivics, tfaith = empireStats(tid)
          local stateName = "NEUTRAL"
          local relScore = 0
          local war = 0
          local griev = 0
          local grievMe = 0
          pcall(function()
            if pDiplo:IsAtWarWith(tid) then war = 1 end
          end)
          -- 不满：UI API；Gameplay 读 PROP_NW_HAIKESI_UI_DIP_from_to
          griev = resolveGrievances(vid, tid)
          grievMe = resolveGrievances(tid, vid)
          -- 关系：对方(tid)对 viewer(vid) 的观感；Index 仅 UI，Script 用 GetDiplomaticState
          stateName = resolveDiploStateName(tid, vid, war == 1)
          relScore = resolveRelScore(tid, vid)
          local modLines = {}
          pcall(function()
            local ai = Players[tid]:GetDiplomaticAI()
            if ai == nil or ai.GetDiplomaticModifiers == nil then return end
            local mods = ai:GetDiplomaticModifiers(vid)
            if mods then
              for _, mod in ipairs(mods) do
                local txt = tostring(mod.Text or ""):gsub("|", "/"):gsub("~", "-"):gsub("\n", " ")
                if txt ~= "" and not string.find(txt, "^LOC_") then
                  table.insert(modLines, (mod.Score or 0) .. "|" .. txt)
                end
              end
            end
          end)
          print("MET|" .. vid .. "|" .. tid .. "|" .. tciv .. "|" .. tleader
            .. "|" .. tscore .. "|" .. tcities .. "|" .. tpop
            .. "|" .. string.format("%.1f", tsci) .. "|" .. string.format("%.1f", tcul) .. "|" .. string.format("%.1f", tgold)
            .. "|" .. tmil .. "|" .. ttechs .. "|" .. tcivics .. "|" .. string.format("%.1f", tfaith)
            .. "|" .. stateName .. "|" .. relScore .. "|" .. war .. "|" .. griev .. "|" .. grievMe)
          for _, ml in ipairs(modLines) do
            print("DIPMOD|" .. vid .. "|" .. tid .. "|" .. ml)
          end
          printVStat(vid, tid, tciv)
        end
      end
    end
    local pVis = PlayersVisibility[vid]
    local myPos = {}
    pcall(function()
      for _, c in Players[vid]:GetCities():Members() do
        table.insert(myPos, {c:GetX(), c:GetY()})
      end
      for _, u in Players[vid]:GetUnits():Members() do
        local ux, uy = u:GetX(), u:GetY()
        if ux ~= -9999 then table.insert(myPos, {ux, uy}) end
      end
    end)
    local threatAgg = {}
    if pVis then
      for pid = 0, 63 do
        if pid ~= vid and Players[pid] and Players[pid]:IsAlive() then
          local ownerName = "Barbarian"
          local isMinor = 0
          if pid ~= 63 then
            local ocfg = PlayerConfigurations[pid]
            if ocfg then ownerName = safeLookup(ocfg:GetCivilizationShortDescription()) end
            if ownerName == "" then ownerName = "Player" .. tostring(pid) end
            pcall(function()
              if Players[pid]:IsMinor() then isMinor = 1 end
            end)
          end
          local atWar = 0
          pcall(function()
            if pid ~= 63 and pDiplo ~= nil and pDiplo:IsAtWarWith(pid) then
              atWar = 1
            end
          end)
          for _, bu in Players[pid]:GetUnits():Members() do
            local bx, by = bu:GetX(), bu:GetY()
            if bx ~= -9999 then
              local visible = false
              pcall(function() visible = pVis:IsVisible(bx, by) end)
              if visible then
                local uType = bu:GetType()
                local entry = uType and GameInfo.Units[uType] or nil
                local bcs = entry and entry.Combat or 0
                local brs = entry and entry.RangedCombat or 0
                if bcs > 0 or brs > 0 then
                  local minDist = 999
                  for _, pos in ipairs(myPos) do
                    local d = Map.GetPlotDistance(pos[1], pos[2], bx, by)
                    if d < minDist then minDist = d end
                  end
                  local agg = threatAgg[pid]
                  if not agg then
                    agg = {name=ownerName, count=0, dist=999, war=atWar, minor=isMinor}
                    threatAgg[pid] = agg
                  end
                  agg.count = agg.count + 1
                  if minDist < agg.dist then agg.dist = minDist end
                end
              end
            end
          end
        end
      end
    end
    for pid, agg in pairs(threatAgg) do
      print("THREAT|" .. vid .. "|" .. pid .. "|" .. agg.name .. "|" .. agg.count
        .. "|" .. agg.dist .. "|" .. tostring(agg.war or 0) .. "|" .. tostring(agg.minor or 0))
    end
    -- 仇水预见：已遇主要文明中、观察者可见城市的可泛滥命名河（对齐 RiverFlood 半径3）
    local CITY_RIVER_RADIUS = 3
    if pVis == nil then
      print("FLOOD_API|" .. vid .. "|0")
    elseif RiverManager == nil or RiverManager.GetRiverForFloodplain == nil then
      print("FLOOD_API|" .. vid .. "|0")
    else
      print("FLOOD_API|" .. vid .. "|1")
      for tid = 0, 62 do
        if tid ~= vid and Players[tid] and Players[tid]:IsAlive() and Players[tid]:IsMajor() then
          local metFlood = false
          pcall(function() metFlood = pDiplo:HasMet(tid) end)
          if metFlood then
            pcall(function()
              for _, city in Players[tid]:GetCities():Members() do
                if city ~= nil then
                  local cx, cy = city:GetX(), city:GetY()
                  local cityVis = false
                  pcall(function() cityVis = pVis:IsVisible(cx, cy) end)
                  if cityVis then
                    local riverSet = {}
                    local nRivers = 0
                    for dx = -CITY_RIVER_RADIUS, CITY_RIVER_RADIUS do
                      for dy = -CITY_RIVER_RADIUS, CITY_RIVER_RADIUS do
                        if Map.GetPlotDistance(cx, cy, cx + dx, cy + dy) <= CITY_RIVER_RADIUS then
                          local plot = Map.GetPlot(cx + dx, cy + dy)
                          if plot ~= nil and plot:GetOwner() == tid then
                            local can = true
                            if RiverManager.CanBeFlooded ~= nil then
                              can = RiverManager.CanBeFlooded(plot) == true
                            end
                            if can then
                              local eRiver = RiverManager.GetRiverForFloodplain(plot:GetX(), plot:GetY())
                              if eRiver ~= nil and eRiver >= 0 then
                                local namedIndex = eRiver
                                if RiverManager.GetRiverType ~= nil then
                                  local okRT, rType = pcall(function()
                                    return RiverManager.GetRiverType(eRiver)
                                  end)
                                  if okRT and rType ~= nil and GameInfo.NamedRivers ~= nil then
                                    local row = GameInfo.NamedRivers[rType]
                                    if row ~= nil and row.Index ~= nil then
                                      namedIndex = row.Index
                                    end
                                  end
                                end
                                if not riverSet[namedIndex] then
                                  local okPlots = true
                                  if RiverManager.GetFloodplainPlots ~= nil then
                                    local plots = RiverManager.GetFloodplainPlots(eRiver)
                                    if plots == nil then
                                      plots = RiverManager.GetFloodplainPlots(namedIndex)
                                    end
                                    if plots == nil then okPlots = false end
                                  end
                                  if okPlots then
                                    riverSet[namedIndex] = true
                                    nRivers = nRivers + 1
                                  end
                                end
                              end
                            end
                          end
                        end
                      end
                    end
                    local cname = safeLookup(city:GetName()):gsub("|", "/")
                    print("FLOOD|" .. vid .. "|" .. tid .. "|" .. tostring(city:GetID())
                      .. "|" .. cname .. "|" .. cx .. "|" .. cy .. "|" .. nRivers)
                  end
                end
              end
            end)
          end
        end
      end
    end
  end
end
end

--- Dump full ExtAI LLM context (same wire lines as SP FireTuner gathers).
-- @param requesterPlayerID number human who triggered the hex
-- @param viewerIDs number[] alive major AI player ids
function Haikesi_DumpExtAIContext(requesterPlayerID, viewerIDs)
  print(CTX_BEGIN)
  pcall(function() dumpOverview(requesterPlayerID) end)
  dumpWorldCongress(requesterPlayerID)
  pcall(function() dumpLeaderViews(viewerIDs or {}) end)
  print(CTX_END)
end

-- Separate AddGameplayScripts files do not share locals; export for GamePlay_Script.
if ExposedMembers ~= nil then
  ExposedMembers.Haikesi_DumpExtAIContext = Haikesi_DumpExtAIContext
end

print("[Haikesi ExtAI Context] dump helpers loaded")
